baseURL = 'https://blog.ekamekas.dev'
languageCode = 'id'
title = 'Fork My Brain'
theme = 'archie'
copyright = 'Â© Mas Eka Setiawan'
staticDir = ['content/static']

# Code Hightlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
pagination.pagerSize = 10

# Other Config
[params]
mode = 'auto'
useCDN = false
subtitle = 'Apa yang ada di kepala, saat ingin menulis, ku tulis di sini. Sekedar software engineering, di tulis dengan 10 jari, vim dan <3.'
mathjax = true
katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ekamekas/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ekamekas/"

[[menu.main]]
name = "Post"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "[Public Key]"
url = "/static/ekamekas.dev.pub"
weight = 3
